# http://localhost:8080/actuator/gateway/routes
server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      routes:
        - id: studentms
          uri: lb://STUDENTMS
          predicates:
            - Path=/studentms/**
          filters:
            - RewritePath=/studentms/(?<path>.*), /$\{path}
        - id: feesms
          uri: lb://FEESMS
          predicates:
            - Path=/feesms/**
          filters:
            - RewritePath=/feesms/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.edu: DEBUG